spring:
  datasource:
    url: jdbc:mysql://1.214.19.22:6002/leafresh
    username: leafresh
    password: leafresh
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop # 운영 환경에서는 create-drop 대신 update 사용 권장
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  mvc:
    static-path-pattern: /static/**

logging:
  level:
    root: INFO
    com.leafresh.oauth: INFO

app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 864000000
  cors:
    allowedOrigins: https://leafresh-frontend.vercel.app
